#!/bin/bash
# Script untuk migrate uploads dari VPS lama ke VPS baru

echo "=== Uploads Migration Tool ==="
echo ""
echo "Pilih cara migrate uploads:"
echo "1. SCP dari VPS lama (167.172.72.73)"
echo "2. Rsync dari VPS lama"
echo "3. Manual copy (tar.gz)"
echo ""

# VPS lama
OLD_VPS="167.172.72.73"
OLD_USER="root"

echo "Cara 1: SCP dari VPS lama"
echo "-------------------------"
echo "Jalankan di VPS BARU (103.118.175.196):"
echo ""
echo "# Buat folder uploads"
echo "mkdir -p /opt/workgrid/server/uploads"
echo ""
echo "# Copy dari VPS lama"
echo "scp -r $OLD_USER@$OLD_VPS:/opt/workgrid/server/uploads/* /opt/workgrid/server/uploads/"
echo ""
echo "# Set permission"
echo "chmod -R 777 /opt/workgrid/server/uploads"
echo ""
echo "# Restart backend"
echo "cd /opt/workgrid && docker compose -f docker-compose.prod.yml restart backend"
echo ""

echo "Cara 2: Backup di VPS lama, restore di VPS baru"
echo "------------------------------------------------"
echo "Jalankan di VPS LAMA (167.172.72.73):"
echo ""
echo "cd /opt/workgrid/server"
echo "tar -czvf uploads-backup.tar.gz uploads/"
echo ""
echo "Kemudian copy ke VPS baru:"
echo "scp uploads-backup.tar.gz root@103.118.175.196:/opt/workgrid/server/"
echo ""
echo "Jalankan di VPS BARU (103.118.175.196):"
echo "cd /opt/workgrid/server"
echo "tar -xzvf uploads-backup.tar.gz"
echo "chmod -R 777 uploads/"
echo "docker compose -f docker-compose.prod.yml restart backend"
