upstream backend {
    server discord_clone_backend:3001;
}

server {
    listen 80;
    server_name workgrid.homeku.net;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name workgrid.homeku.net;
    
    root /usr/share/nginx/html;
    index index.html;
    
    ssl_certificate /etc/letsencrypt/live/workgrid.homeku.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/workgrid.homeku.net/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1024;
    
    location ^~ /uploads/ {
        proxy_pass http://backend/uploads/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /socket.io/ {
        proxy_pass http://backend/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
